target/rockchip: radxa e24c retry rtc binding
Signed-off-by: Liangbin Lian <jjm2473@gmail.com>

diff --git a/target/linux/rockchip/armv8/base-files/lib/preinit/04_board b/target/linux/rockchip/armv8/base-files/lib/preinit/04_board
--- a/target/linux/rockchip/armv8/base-files/lib/preinit/04_board
+++ b/target/linux/rockchip/armv8/base-files/lib/preinit/04_board
@@ -40,4 +40,14 @@ preinit_gpio() {
 	esac
 }
 
+preinit_rebind_drivers() {
+	case $(board_name) in
+	radxa,e24c)
+		# rebind e24c hym8563 if previously bound failed
+		[ -e /sys/bus/i2c/drivers/rtc-hym8563/3-0051 ] || { echo "3-0051" > /sys/bus/i2c/drivers/rtc-hym8563/bind; }
+	;;
+	esac
+}
+
 boot_hook_add preinit_main preinit_gpio
+boot_hook_add preinit_main preinit_rebind_drivers
